#!/bin/bash
#1.Add user to run the app

sudo useradd -m -d /home/railsplay railsplay -s /bin/bash

#2.Next, Upgrade the system and install in case something missing

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y git git-core zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev nodejs

#3.cd to new user's home dir and clone the remote repository to the new user's home dir 
sudo su - railsplay -c "git clone https://github.com/nataliiapakhol/railsplay.git"

#4.Install ruby 2.5.1(used version while creating)
sudo su - railsplay -c "wget http://ftp.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.gz"
sudo su - railsplay -c "tar -xzvf ruby-2.5.1.tar.gz"
sudo su - railsplay -c "(cd /home/railsplay/ruby-2.5.1;/home/railsplay/ruby-2.5.1/configure)"
sudo su - railsplay -c "(cd /home/railsplay/ruby-2.5.1;/usr/bin/make)"
(cd /home/railsplay/ruby-2.5.1;sudo /usr/bin/make install)

#5.Install Bundler&Rails
(cd /home/railsplay/railsplay;sudo /usr/local/bin/gem install bundler)
(cd /home/railsplay/railsplay;curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -)
(cd /home/railsplay/railsplay;sudo apt-get install -y nodejs)
(cd /home/railsplay/railsplay;bundle install)

sudo su - railsplay -c "(cd /home/railsplay/railsplay/bin;rails db:migrate RAILS_ENV=development)"
sudo su - railsplay -c "(cd /home/railsplay/railsplay;bin/rails server)"

